Fix for V3: Prevent a selected option from being removed when isDisabled is passed
csandman/chakra-react-select pull request #302
Opened 2023-11-10 09:07 UTC by lschlesinger

Issue: users can remove selected options when isDisabled is passed when using V3 version of chakra-react-select

Reported here for v4:  https://github.com/csandman/chakra-react-select/issues/168
Fixed here for > v4: https://github.com/csandman/chakra-react-select/pull/169

This PR aims to fix this issue for v3 versions

2023-11-13 18:02 UTC, csandman commented on src/chakra-components/containers.tsx
>    };
```suggestion
    ...(isDisabled ? { cursor: "not-allowed" } : {}),
  };
```

2023-11-13 18:03 UTC, csandman requested changes
This works for me, can you make the one change I requested first though? Just want this to better line up with the intent of my original change!

2023-11-16 13:29 UTC, lschlesinger commented
@csandman Thanks for the feedback, I've changed it now.

2023-11-16 22:41 UTC, merged

2023-11-16 22:49 UTC, csandman commented
Great, looks good! Merged and released in [`v3.3.10`](https://github.com/csandman/chakra-react-select/releases/tag/v3.3.10)!